on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: iffy/install-nim@v5
        with:
          version: binary:stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: nimble install -y

      - name: Test
        run: nimble test

      - name: Check
        run: nimble check
